<a href="https://colab.research.google.com/github/kevinmultazam/claude-code-kevin/blob/main/Another_copy_of_PemrosesanTeksPertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install git+https://github.com/tweepy/tweepy.git

Collecting git+https://github.com/tweepy/tweepy.git
  Cloning https://github.com/tweepy/tweepy.git to /tmp/pip-req-build-nw88jdjk
  Running command git clone --filter=blob:none --quiet https://github.com/tweepy/tweepy.git /tmp/pip-req-build-nw88jdjk
  Resolved https://github.com/tweepy/tweepy.git to commit c05ba988177219f1591b3bf03b8896b427c8b233
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from tweepy==4.16.0) (3.3.1)
Requirement already satisfied: requests<3,>=2.27.0 in /usr/local/lib/python3.12/dist-packages (from tweepy==4.16.0) (2.32.4)
Requirement already satisfied: requests-oauthlib<3,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tweepy==4.16.0) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy==4.16.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy==4.16.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy==4.16.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy==4.16.0) (2026.4.22)

##Autentikasi ke Twitter

In [ ]:
import tweepy
import csv

api_key = "sTbzeu67tIzMIMNHl83MblzMZ"
api_key_secret = "PL3G5G2gndlQndLs8yvNjl5SgfuiYWwU8yzgEwVi6tRylg5DnI"
access_token = "1532674693106642944-xHh6wjmKGXWbgNeOcgkdkJrDihvXM5"
access_token_secret = "Uz0HmlVmB0fWwIauBh557G13fHdYZT1vMpBUHQssRrlpt"

auth = tweepy.OAuthHandler(api_key,api_key_secret)
auth.set_access_token(access_token,access_token_secret)

api = tweepy.API(auth)

try:
  api.verify_credentials()
  print("Berhasil")
except:
  print("Gagal")

Gagal

In [ ]:
timeline = api.home_timeline()

for tweet in timeline:
  print(tweet.text)

Forbidden: 403 Forbidden
453 - You currently have access to a subset of X API V2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.x.com/en/portal/product

##Mengambil data user

In [ ]:
# Make sure tweepy is installed and up-to-date
!pip install --upgrade tweepy

# ... (previous code for authentication) ...

user = api.get_user(screen_name="TolakKenaikanPPN12Persen") # Explicitly use screen_name

print("Nama: " + user.name)
print("Akun: @" + user.screen_name)
print("Lokasi: " + user.location)
print("Deskripsi: " + user.description)

Requirement already satisfied: tweepy in /usr/local/lib/python3.11/dist-packages (4.15.0)
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from tweepy) (3.2.2)
Requirement already satisfied: requests<3,>=2.27.0 in /usr/local/lib/python3.11/dist-packages (from tweepy) (2.32.3)
Requirement already satisfied: requests-oauthlib<3,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from tweepy) (2.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27.0->tweepy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27.0->tweepy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27.0->tweepy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27.0->tweepy) (2025.4.26)

Forbidden: 403 Forbidden
453 - You currently have access to a subset of X API V2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.x.com/en/portal/product

##Mengambil data trend

In [ ]:
trends = api.get_place_trends(1030077)
trends

##Pencarian data

In [ ]:
search = api.search_tweets(q="Hapsun", count=30) #count max 100
for tw in search:
  print(tw.text)

In [ ]:
#mengguankan cursor/pagination
#item = jumlah data yang ingin diambil keseluruhan
#count = jumlah maksimal data tiap halaman
import pandas as pd
for tweet in tweepy.Cursor(api.search_tweets, "LGBT", count=200, lang="id").items(1000):
    hasil = {'Screen Name':[tweet.user.screen_name],'Text':[tweet.text],'Replies':[tweet.user.listed_count],'Retweets':[tweet.retweet_count],'Likes':[tweet.favorite_count]}
    print(hasil)

In [ ]:
import json
import re
import io

fname="dataset"

def create_dataset(api_key,api_secret,access_token,access_secret):
  with open('%s.csv' % (fname), 'w', encoding="utf-8") as file:
    w = csv.writer(file, delimiter='|')
    w.writerow(['Screen Name', 'Text', 'Replies', 'Retweets','Likes'])

        # For each tweet matching hashtag, write relevant info to the spreadsheet
    for tweet in tweepy.Cursor(api.search_tweets, "Hepatitis", count=200,tweet_mode='extended'lang="id").items(2000):
        w.writerow([tweet.user.screen_name,
                  tweet.full_text.replace('\n',' '),
                  tweet.user.listed_count,
                  tweet.retweet_count,
                  tweet.favorite_count])

if __name__ == '__main__':
  create_dataset(api_key,api_key_secret,access_token,access_token_secret)

SyntaxError: ignored

In [ ]:
import pandas as pd
db=pd.read_csv('dataset.csv',delimiter='|')
db

,Screen Name,Text,Replies,Retweets,Likes
0,SakiinaQhiCO_33,RT @catatankaqihati: Vaksin covid 19 untuk ana...,1,18,0
1,GiovannaSmedick,RT @YohanessssW: Pandemi Covid-19 msh blm sepe...,0,218,0
2,RisingerTabetha,RT @YohanessssW: Pandemi Covid-19 msh blm sepe...,0,218,0
3,DanaePote,RT @YohanessssW: Pandemi Covid-19 msh blm sepe...,0,218,0
4,AntonyBelardo,RT @YohanessssW: Pandemi Covid-19 msh blm sepe...,0,218,0
...,...,...,...,...,...
1995,kbearries,Tau gak sih guys kalo hepatitis akut memang se...,0,0,1
1996,njmcxs,Aku lebih milih tetep pake masker sih #TetapSe...,0,0,0
1997,CahyoRara,waspada terhadap penularan penyakit apapun ter...,0,0,0
1998,nelawin2,lagi rame hepatitis akut ini #TetapSehatPakaiM...,0,0,0
1999,Orobinxq,"RT @YohanessssW: Yuk, kawan-kawan, tetap #paka...",0,175,0

In [ ]:
df = db.drop_duplicates(subset=["Text"], keep='first')
df

,Screen Name,Text,Replies,Retweets,Likes
0,nraviet,Selesai covid berlanjut hepatitis sekarang cac...,0,0,0
1,AndraGonsales,RT @TTelisik: Kemenkes menyatakan bahwa faktan...,0,4,0
2,kurakuraninjaid,@pertiwi86957822 Infrastruktur Indonesia Hebat...,0,0,0
3,kurakuraninjaid,Hepatitis tidak ada hubungannya dengan vaksina...,0,0,0
4,SutanSee,Vaksin Covid Telah Teruji &amp; Terjamin Aman ...,0,0,0
...,...,...,...,...,...
758,sorentah,Hepatitis akut bukan tipe penyakit yang tiba-t...,0,0,0
759,mcdpil,perlu diwaspadai sekarang ada penyebaran hepat...,6,0,2
760,brasndi32,Diduga penyebaran Hepatitis akut ini memang me...,0,0,0
761,LastWota,RT @KCahyanii14: Dugaan keempat adalah patogen...,8,1,0
762,MinicornStore,https://t.co/0znrgteIvl Hepatitis akut bkn tip...,0,0,0

In [ ]:
df.to_csv("tweetLGBT.csv", sep="|", index=False)